# Generated by Django 2.1 on 2018-08-15 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_model', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Cars')),
            ],
        ),
    ]
