# Generated by Django 2.1 on 2018-09-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=100, unique=True)),
                ('user_password', models.CharField(max_length=100)),
                ('user_gender', models.CharField(max_length=100)),
                ('user_qualification', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'emp_table',
            },
        ),
    ]
